### ISSUE TITLE
Legacy console sidebar for SPC

### ISSUE THREAD

**Issue by misterbisson** [joyent/webconsole-navigation#42]
Reviewing the sidebar menu in https://my-stg.samsungcloud.io/main, I see the following:

- Dashboard
- Compute
  - Instances
  - Custom Images
  - Docker Images
  - Docker Registries
- Network
  - Networks
  - VLANs
  - Firewall
- Storage
  - File Manager
  - ~Job Builder~
  - ~Job History~
  - ~Fastly CDN~
- Access
  - Users
  - Roles
  - Policies
- Getting Started

Please remove the items with a strike-through in that list. Reason:

- Manta jobs are not supported in SPC per MANTA-3583 and others.
- Fastly CDN is not supported/relevant for SPC

**Comment by geek** [comment]
@misterbisson I moved this issue
